FROM node:22-alpine AS builder

WORKDIR /server

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /server

COPY --from=builder /server/package*.json ./
COPY --from=builder /server/node_modules ./node_modules
COPY --from=builder /server/dist ./dist

EXPOSE 3000

CMD ["node", "dist/server.js"]